# Generated by Django 5.0.2 on 2024-02-16 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djangoapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CarModel",
        ),
    ]
